X Variables = Aggregate the following values by search date/time 
    videoTitleSentimentScore_pos = vader pos label for video title
    captionSentimentScore_pos = vader pos label for caption string
    viewcounts_weighted = views count / number of day since published
    like_count_weighted = like count / number of day since published
    dislike_count_weighted = dislike count / number of day since published
    like_dislike_ratio = like / (like + dislike)
    like_dislike_ratio_by_viewcounts_weighted = like dislike ration * viewcount_weight
    
Y Variable (Classifier) *Need to investigate %change
    Hold = 0 (Precent change 0% - 3%)
    Buy = 1 (Precent change > 3%)
    Sell = 2 ((Precent change < -3%)
        Interval of 5 days
        
Y Variable (Numerical)
    Future percent change (1Day)
    Future percent change (3Day)
    Future percent change (5Day)
    Future percent change (7Day)
    Future percent change (14Day)

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

### Feature Built Data Set load

In [2]:
#load cleaned and feature built data set
nvidia_sent_df = pd.read_csv("../00_data/Feature_Built_Sent_Data_22MAR.gz", compression="gzip") #, index_col = "Date")

In [3]:
nvidia_sent_df = nvidia_sent_df.drop(["Unnamed: 0"], axis=1)

In [4]:
nvidia_sent_df.set_index('Date')

videoTitleSentimentScore_pos  videoTitleSentimentScore_neg  \
Date                                                                     
2020-10-02                      0.081317                      0.099751   
2020-10-03                      0.059800                      0.065880   
2020-10-04                      0.066000                      0.059480   
2020-10-05                      0.071018                      0.065469   
2020-10-06                      0.066353                      0.069018   
...                                  ...                           ...   
2021-03-15                      0.037338                      0.033960   
2021-03-16                      0.037245                      0.064280   
2021-03-17                      0.038080                      0.066406   
2021-03-18                      0.051550                      0.061970   
2021-03-19                      0.042326                      0.062851   

            captionSentimentScore_pos  captionSentimentScore_neg  \
Date                                                               
2020-10-02                   0.102556                   0.036249   
2020-10-03                   0.116100                   0.034660   
2020-10-04                   0.110600                   0.035320   
2020-10-05                   0.110771                   0.031495   
2020-10-06                   0.110309                   0.031280   
...                               ...                        ...   
2021-03-15                   0.087764                   0.030724   
2021-03-16                   0.105100                   0.034100   
2021-03-17                   0.102891                   0.033063   
2021-03-18                   0.099855                   0.031660   
2021-03-19                   0.109966                   0.036794   

            num_days_since_pub  viewcounts_weighted  like_count_weighted  \
Date                                                                       
2020-10-02           17.925926         71814.282680          3271.401019   
2020-10-03           35.600000         71921.099664          3523.220911   
2020-10-04           21.680000         66084.953130          3030.285674   
2020-10-05           19.829091         61208.718514          3150.355807   
2020-10-06           19.432727         72276.063635          3948.601316   
...                        ...                  ...                  ...   
2021-03-15          109.768889         15241.801392          1049.344298   
2021-03-16          108.970000         14870.723784          1032.050839   
2021-03-17          111.137143         14748.626569           939.470945   
2021-03-18          107.740000         15558.251680          1049.395704   
2021-03-19          110.005714         15417.660309          1121.427479   

            like_dislike_ratio  weighted_like_dislike_ratio  \
Date                                                          
2020-10-02            0.969752                     0.969752   
2020-10-03            0.969585                     0.969585   
2020-10-04            0.972772                     0.972772   
2020-10-05            0.971021                     0.971021   
2020-10-06            0.972598                     0.972598   
...                        ...                          ...   
2021-03-15            0.955442                     0.955442   
2021-03-16            0.954523                     0.954523   
2021-03-17            0.956001                     0.956001   
2021-03-18            0.956913                     0.956913   
2021-03-19            0.957292                     0.957292   

            like_dislike_ratio_by_viewcounts_weighted       index  \
Date                                                                
2020-10-02                               69921.826086  2020-10-02   
2020-10-03                               70150.404005  2020-10-03   
2020-10-04                               64444.365869  2020-10-04   
2020-10-05

In [5]:
nvidia_sent_df.action.value_counts()

hold    66
sell    26
buy     24
Name: action, dtype: int64

In [6]:
test_slip_percentage = .35
split_loc = int(len(nvidia_sent_df) - (len(nvidia_sent_df)* test_slip_percentage))
X = nvidia_sent_df.iloc[0:,1:-4]
X_train = nvidia_sent_df.iloc[0:split_loc,1:-4]
y_train = nvidia_sent_df.iloc[0:split_loc,-2]
X_test = nvidia_sent_df.iloc[split_loc:,1:-4]
y_test = nvidia_sent_df.iloc[split_loc:,-2]

In [7]:
y_test = y_test.fillna('hold')

In [8]:
enc = LabelEncoder()
enc.fit(y_train.values.reshape(-1, 1))
y_train = enc.transform(y_train.values)
y_test = enc.transform(y_test.values)

C:\Users\Chris\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [9]:
X_train

videoTitleSentimentScore_pos  videoTitleSentimentScore_neg  \
0                       0.081317                      0.099751   
1                       0.059800                      0.065880   
2                       0.066000                      0.059480   
3                       0.071018                      0.065469   
4                       0.066353                      0.069018   
..                           ...                           ...   
71                      0.052687                      0.099367   
72                      0.054947                      0.109147   
73                      0.048684                      0.104538   
74                      0.038840                      0.075400   
75                      0.049451                      0.100887   

    captionSentimentScore_pos  captionSentimentScore_neg  num_days_since_pub  \
0                    0.102556                   0.036249           17.925926   
1                    0.116100                   0.034660           35.600000   
2                    0.110600                   0.035320           21.680000   
3                    0.110771                   0.031495           19.829091   
4                    0.110309                   0.031280           19.432727   
..                        ...                        ...                 ...   
71                   0.093160                   0.029447          103.650909   
72                   0.099476                   0.035200           99.524444   
73                   0.095898                   0.032345          100.756364   
74                   0.092180                   0.025340          102.880000   
75                   0.090793                   0.027967          100.821818   

    viewcounts_weighted  like_count_weighted  like_dislike_ratio  \
0          71814.282680          3271.401019            0.969752   
1          71921.099664          3523.220911            0.969585   
2          66084.953130          3030.285674            0.972772   
3          61208.718514          3150.355807            0.971021   
4          72276.063635          3948.601316            0.972598   
..                  ...                  ...                 ...   
71         40884.294912          2333.477526            0.960862   
72         39150.244532          2095.016744            0.962701   
73         32371.374164          1724.886761            0.961828   
74         24608.052526          1246.911761            0.959587   
75         20121.328349           975.258891            0.953411   

    weighted_like_dislike_ratio  like_dislike_ratio_by_viewcounts_weighted  
0                      0.969752                               69921.826086  
1                      0.969585                               70150.404005  
2                      0.972772                               64444.365869  
3                      0.971021                               59725.066775  
4                      0.972598                               70807.388299  
..                          ...                                        ...  
71                     0.960862                               39957.921107  
72                     0.962701                               38150.067899  
73                     0.961828                               31501.578177  
74                     0.959587                               23895.981040  
75                     0.953411                               19491.439493  

[76 rows x 10 columns]

In [10]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0).fit(X_train, y_train)
clf.score(X_test, y_test)

C:\Users\Chris\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.4523809523809524

In [11]:
from sklearn import metrics
predictions = clf.predict(X_test)
cm = metrics.confusion_matrix(y_test, predictions)
print(cm)

[[ 0 11  0]
 [ 0 19  0]
 [ 0 12  0]]


In [12]:
predictions

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [13]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
scaler.transform(X)

array([[ 1.2052249 ,  1.36555961, -0.36426072, ...,  0.8571206 ,
         0.8571206 ,  2.62085062],
       [ 0.07602105,  0.40072427,  1.05325032, ...,  0.83300792,
         0.83300792,  2.63353908],
       [ 0.4013877 ,  0.21841825,  0.47764083, ...,  1.29333307,
         1.29333307,  2.31679435],
       ...,
       [-1.06381177,  0.41569941, -0.32910951, ..., -1.12917796,
        -1.12917796, -0.46238978],
       [-0.3569265 ,  0.28934669, -0.6468908 , ..., -0.99748368,
        -0.99748368, -0.41885226],
       [-0.84100309,  0.31445446,  0.41125885, ..., -0.9427089 ,
        -0.9427089 , -0.42513595]])

In [14]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0).fit(scaler.transform(X_train), y_train)
clf.score(scaler.transform(X_test), y_test)

0.35714285714285715

In [15]:
from sklearn import metrics
from sklearn.metrics import roc_auc_score
predictions = clf.predict(scaler.transform(X_test))
cm = metrics.confusion_matrix(y_test, predictions)
print(cm)
score = roc_auc_score(y_test, clf.predict_proba(scaler.transform(X_test)), multi_class='ovr')
print(score)

[[ 1  5  5]
 [ 2 12  5]
 [ 1  9  2]]
0.3344655183512495


In [16]:
predictions 

array([1, 1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 2, 2, 2, 1, 1])

### Neural Network

In [17]:
from sklearn.metrics import accuracy_score
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(max_iter=2000).fit(X_train, y_train)
inner_score = clf.score(X_test, y_test)
predictions = clf.predict(X_test)
cm = metrics.confusion_matrix(y_test, predictions)

In [18]:
inner_score 

0.4523809523809524

In [19]:
cm

array([[ 0, 11,  0],
       [ 0, 19,  0],
       [ 0, 12,  0]], dtype=int64)

In [20]:
clf = MLPClassifier(max_iter=2000).fit(scaler.transform(X_train), y_train)
score = clf.score(scaler.transform(X_test), y_test)
predictions = clf.predict(scaler.transform(X_test))
cm = metrics.confusion_matrix(y_test, predictions)
print(score)
print(cm)

0.19047619047619047
[[ 8  3  0]
 [19  0  0]
 [12  0  0]]


In [21]:
from sklearn import preprocessing

scaler = preprocessing.StandardScaler().fit(X_train)

In [22]:
X_train

videoTitleSentimentScore_pos  videoTitleSentimentScore_neg  \
0                       0.081317                      0.099751   
1                       0.059800                      0.065880   
2                       0.066000                      0.059480   
3                       0.071018                      0.065469   
4                       0.066353                      0.069018   
..                           ...                           ...   
71                      0.052687                      0.099367   
72                      0.054947                      0.109147   
73                      0.048684                      0.104538   
74                      0.038840                      0.075400   
75                      0.049451                      0.100887   

    captionSentimentScore_pos  captionSentimentScore_neg  num_days_since_pub  \
0                    0.102556                   0.036249           17.925926   
1                    0.116100                   0.034660           35.600000   
2                    0.110600                   0.035320           21.680000   
3                    0.110771                   0.031495           19.829091   
4                    0.110309                   0.031280           19.432727   
..                        ...                        ...                 ...   
71                   0.093160                   0.029447          103.650909   
72                   0.099476                   0.035200           99.524444   
73                   0.095898                   0.032345          100.756364   
74                   0.092180                   0.025340          102.880000   
75                   0.090793                   0.027967          100.821818   

    viewcounts_weighted  like_count_weighted  like_dislike_ratio  \
0          71814.282680          3271.401019            0.969752   
1          71921.099664          3523.220911            0.969585   
2          66084.953130          3030.285674            0.972772   
3          61208.718514          3150.355807            0.971021   
4          72276.063635          3948.601316            0.972598   
..                  ...                  ...                 ...   
71         40884.294912          2333.477526            0.960862   
72         39150.244532          2095.016744            0.962701   
73         32371.374164          1724.886761            0.961828   
74         24608.052526          1246.911761            0.959587   
75         20121.328349           975.258891            0.953411   

    weighted_like_dislike_ratio  like_dislike_ratio_by_viewcounts_weighted  
0                      0.969752                               69921.826086  
1                      0.969585                               70150.404005  
2                      0.972772                               64444.365869  
3                      0.971021                               59725.066775  
4                      0.972598                               70807.388299  
..                          ...                                        ...  
71                     0.960862                               39957.921107  
72                     0.962701                               38150.067899  
73                     0.961828                               31501.578177  
74                     0.959587                               23895.981040  
75                     0.953411                               19491.439493  

[76 rows x 10 columns]

In [23]:
from sklearn import preprocessing

scaler = preprocessing.StandardScaler().fit(X_train)

### Keras Trial 

### APPENDIX

In [98]:
from keras.layers import Dense
from keras.models import Sequential
from keras.utils import to_categorical
import numpy as np
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from keras.layers import Dense, Embedding, LSTM, SpatialDropout1D
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Conv2D, Flatten, Dense
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
from keras.utils.np_utils import to_categorical
from keras.callbacks import EarlyStopping
from numpy import mean
from numpy import std
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import RepeatedKFold
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import accuracy_score
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier

In [134]:
nvidia_sent_df_lstm = pd.read_csv("../00_data/Cleaned_Sent_Data_16MAR_v3.gz", compression="gzip", index_col = "index")

In [135]:
nvidia_sent_df_lstm.drop(labels=['Unnamed: 0'], axis=1,inplace = True)
nvidia_sent_df_lstm.drop(labels=['Date'], axis=1,inplace = True)
nvidia_sent_df_lstm.head()

videoTitleSentimentScore_pos  videoTitleSentimentScore_neg  \
index                                                                    
2020-10-02                      0.081317                      0.099751   
2020-10-03                      0.059800                      0.065880   
2020-10-04                      0.066000                      0.059480   
2020-10-05                      0.071018                      0.065469   
2020-10-06                      0.066353                      0.069018   

            captionSentimentScore_pos  captionSentimentScore_neg  \
index                                                              
2020-10-02                   0.102556                   0.036249   
2020-10-03                   0.116100                   0.034660   
2020-10-04                   0.110600                   0.035320   
2020-10-05                   0.110771                   0.031495   
2020-10-06                   0.110309                   0.031280   

            num_days_since_pub  viewcounts_weighted  like_count_weighted  \
index                                                                      
2020-10-02           17.925926         71814.282680          3271.401019   
2020-10-03           35.600000         71921.099664          3523.220911   
2020-10-04           21.680000         66084.953130          3030.285674   
2020-10-05           19.829091         61208.718514          3150.355807   
2020-10-06           19.432727         72276.063635          3948.601316   

            like_dislike_ratio  weighted_like_dislike_ratio  \
index                                                         
2020-10-02            0.969752                     0.969752   
2020-10-03            0.969585                     0.969585   
2020-10-04            0.972772                     0.972772   
2020-10-05            0.971021                     0.971021   
2020-10-06            0.972598                     0.972598   

            like_dislike_ratio_by_viewcounts_weighted  percent_change action  \
index                                                                          
2020-10-02                               69921.826086        0.044362    buy   
2020-10-03                               70150.404005        0.041791    buy   
2020-10-04                               64444.365869        0.022541   hold   
2020-10-05                               59725.066775        0.013192   hold   
2020-10-06                               70807.388299       -0.022469   hold   

           _merge  
index              
2020-10-02   both  
2020-10-03   both  
2020-10-04   both  
2020-10-05   both  
2020-10-06   both

In [143]:
X = nvidia_sent_df_lstm.iloc[0:,0:-3]
y = nvidia_sent_df_lstm.iloc[0:,-2]

In [144]:
print(X.shape)
print(y.shape)

(92, 10)
(92,)


In [145]:
scaler = MinMaxScaler(feature_range=(0, 1))
X = scaler.fit_transform(X)
X = pd.DataFrame(X)

In [147]:
y = pd.get_dummies(y)

In [149]:
X = X.values
Y = y.values

In [150]:
# First define baseline model. Then use it in Keras Classifier for the training
def baseline_model():
    # Create model here
    model = Sequential()
    model.add(Dense(15, input_dim = 48, activation = 'relu')) # Rectified Linear Unit Activation Function
    model.add(Dense(15, activation = 'relu'))
    model.add(Dense(11, activation = 'softmax')) # Softmax for multi-class classification
    # Compile model here
    model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
    return model

In [158]:
from keras.wrappers.scikit_learn import KerasClassifier
# Create Keras Classifier and use predefined baseline model
estimator = KerasClassifier(build_fn = baseline_model, epochs = 5, batch_size = 2, verbose = 0)
# Try different values for epoch and batch size

In [159]:
from sklearn.model_selection import KFold
kfold = KFold(n_splits = 5, shuffle = True, random_state = 82)

In [160]:
from sklearn.model_selection import cross_val_score
# Object to describe the result
results = cross_val_score(estimator, X, Y, cv = kfold)
# Result
print("Result: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

Result: nan% (nan%)


In [70]:
test_slip_percentage = .30
split_loc = int(len(nvidia_sent_df) - (len(nvidia_sent_df)* test_slip_percentage))
X = nvidia_sent_df.iloc[0:,1:-4]
X_train = nvidia_sent_df.iloc[0:split_loc,1:-4]
y_train = nvidia_sent_df.iloc[0:split_loc,-2]
X_test = nvidia_sent_df.iloc[split_loc:,1:-4]
y_test = nvidia_sent_df.iloc[split_loc:,-2]

In [74]:
#change buy sell hold ot 0: Buy, 1: sell, 2: hold
# y_train = y_train.replace("buy", 0)
# y_train = y_train.replace("sell", 1)
# y_train = y_train.replace("hold", 2)

In [101]:
X

Date  videoTitleSentimentScore_pos  videoTitleSentimentScore_neg  \
0   2020-10-02                      0.081317                      0.099751   
1   2020-10-03                      0.059800                      0.065880   
2   2020-10-04                      0.066000                      0.059480   
3   2020-10-05                      0.071018                      0.065469   
4   2020-10-06                      0.066353                      0.069018   
..         ...                           ...                           ...   
87  2021-02-15                      0.034680                      0.077251   
88  2021-02-16                      0.040633                      0.051960   
89  2021-02-18                      0.046834                      0.058583   
90  2021-02-19                      0.033890                      0.069657   
91  2021-02-20                      0.045380                      0.073320   

    captionSentimentScore_pos  captionSentimentScore_neg  num_days_since_pub  \
0                    0.102556                   0.036249           17.925926   
1                    0.116100                   0.034660           35.600000   
2                    0.110600                   0.035320           21.680000   
3                    0.110771                   0.031495           19.829091   
4                    0.110309                   0.031280           19.432727   
..                        ...                        ...                 ...   
87                   0.107473                   0.031818          115.607273   
88                   0.102418                   0.032844          120.298182   
89                   0.101794                   0.032863          119.245714   
90                   0.097573                   0.031320          113.623333   
91                   0.103120                   0.034700          101.600000   

    viewcounts_weighted  like_count_weighted  like_dislike_ratio  \
0          71814.282680          3271.401019            0.969752   
1          71921.099664          3523.220911            0.969585   
2          66084.953130          3030.285674            0.972772   
3          61208.718514          3150.355807            0.971021   
4          72276.063635          3948.601316            0.972598   
..                  ...                  ...                 ...   
87         13347.728400           693.672590            0.956675   
88         25551.254491          1678.468242            0.960266   
89         16224.086329           939.047614            0.954441   
90         19150.754564          1316.566845            0.958693   
91         41163.221800          3604.290577            0.958253   

    weighted_like_dislike_ratio  like_dislike_ratio_by_viewcounts_weighted  
0                      0.969752                               69921.826086  
1                      0.969585                               70150.404005  
2                      0.972772                               64444.365869  
3                      0.971021                               59725.066775  
4                      0.972598                               70807.388299  
..                          ...                                        ...  
87                     0.956675                               12957.795705  
88                     0.960266                               25040.842574  
89                     0.954441                               15837.504011  
90                     0.958693                               18586.708998  
91                     0.958253                               40312.584142  

[92 rows x 11 columns]

In [79]:
# get the model
def get_model(n_inputs, n_outputs):
    model = Sequential()
    model.add(Dense(20, input_dim=n_inputs, kernel_initializer='he_uniform', activation='relu'))
    model.add(Dense(n_outputs, activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam')
    return model

In [80]:
get_model(len(X_train), 3)

In [95]:
X_train.shape[1]

(64, 11)

In [99]:
# evaluate a model using repeated k-fold cross-validation
def evaluate_model(X, y):
    results = list()
    n_inputs, n_outputs = X.shape[1], y.nunique()
    # define evaluation procedure
    cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)
    # enumerate folds
    for train_ix, test_ix in cv.split(X):
        # prepare data
        X_train, X_test = X[train_ix], X[test_ix]
        y_train, y_test = y[train_ix], y[test_ix]
        # define model
        model = get_model(n_inputs, n_outputs)
        # fit model
        model.fit(X_train, y_train, verbose=0, epochs=100)
        # make a prediction on the test set
        yhat = model.predict(X_test)
        # round probabilities to class labels
        yhat = yhat.round()
        # calculate accuracy
        acc = accuracy_score(y_test, yhat)
        # store result
        print('>%.3f' % acc)
        results.append(acc)
    return results

In [100]:
evaluate_model(X_train, y_train)

KeyError: "None of [Int64Index([ 0,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,\n            18, 19, 20, 22, 23, 25, 26, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,\n            38, 40, 41, 42, 43, 45, 46, 47, 48, 49, 50, 51, 53, 54, 55, 56, 57,\n            58, 59, 60, 61, 62, 63],\n           dtype='int64')] are in the [columns]"

In [66]:
print((X_train.shape, y_train.shape, X_test.shape, y_test.shape))

model = Sequential()
model.add(Embedding(n_most_common_words, emb_dim, input_length=X.shape[1]))
model.add(SpatialDropout1D(0.7))
model.add(LSTM(64, dropout=0.7, recurrent_dropout=0.7))
model.add(Dense(4, activation='softmax'))
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])
print(model.summary())
history = model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size,validation_split=0.2,callbacks=[EarlyStopping(monitor='val_loss',patience=7, min_delta=0.0001)])

((64, 11), (64,), (28, 11), (28,))


NameError: name 'n_most_common_words' is not defined

In [ ]:
nvidia_sent_df_lstm = nvidia_sent_df.drop(["Date"], axis=1)

In [45]:
date = nvidia_sent_df_lstm["index"]
nvidia_sent_df_lstm.drop(labels=['index'], axis=1,inplace = True)
nvidia_sent_df_lstm.insert(0, 'Date', date)
nvidia_sent_df_lstm.drop(labels=['Unnamed: 0'], axis=1,inplace = True)

ValueError: cannot insert Date, already exists

In [24]:
# Make sure that you have all these libaries available to run the code successfully
# from pandas_datareader import data
import matplotlib.pyplot as plt
import pandas as pd
import datetime as dt
import urllib.request, json
import os
import numpy as np
import tensorflow as tf # This code has been tested with TensorFlow 1.6
from sklearn.preprocessing import MinMaxScaler

In [39]:
nvidia_sent_df_lstm = nvidia_sent_df.drop(["Date"], axis=1)

In [40]:
date = nvidia_sent_df_lstm["index"]
nvidia_sent_df_lstm.drop(labels=['index'], axis=1,inplace = True)
nvidia_sent_df_lstm.insert(0, 'Date', date)
nvidia_sent_df_lstm.drop(labels=['Unnamed: 0'], axis=1,inplace = True)

In [41]:
nvidia_sent_df_lstm

Date  videoTitleSentimentScore_pos  videoTitleSentimentScore_neg  \
0   2020-10-02                      0.081317                      0.099751   
1   2020-10-03                      0.059800                      0.065880   
2   2020-10-04                      0.066000                      0.059480   
3   2020-10-05                      0.071018                      0.065469   
4   2020-10-06                      0.066353                      0.069018   
..         ...                           ...                           ...   
87  2021-02-15                      0.034680                      0.077251   
88  2021-02-16                      0.040633                      0.051960   
89  2021-02-18                      0.046834                      0.058583   
90  2021-02-19                      0.033890                      0.069657   
91  2021-02-20                      0.045380                      0.073320   

    captionSentimentScore_pos  captionSentimentScore_neg  num_days_since_pub  \
0                    0.102556                   0.036249           17.925926   
1                    0.116100                   0.034660           35.600000   
2                    0.110600                   0.035320           21.680000   
3                    0.110771                   0.031495           19.829091   
4                    0.110309                   0.031280           19.432727   
..                        ...                        ...                 ...   
87                   0.107473                   0.031818          115.607273   
88                   0.102418                   0.032844          120.298182   
89                   0.101794                   0.032863          119.245714   
90                   0.097573                   0.031320          113.623333   
91                   0.103120                   0.034700          101.600000   

    viewcounts_weighted  like_count_weighted  like_dislike_ratio  \
0          71814.282680          3271.401019            0.969752   
1          71921.099664          3523.220911            0.969585   
2          66084.953130          3030.285674            0.972772   
3          61208.718514          3150.355807            0.971021   
4          72276.063635          3948.601316            0.972598   
..                  ...                  ...                 ...   
87         13347.728400           693.672590            0.956675   
88         25551.254491          1678.468242            0.960266   
89         16224.086329           939.047614            0.954441   
90         19150.754564          1316.566845            0.958693   
91         41163.221800          3604.290577            0.958253   

    weighted_like_dislike_ratio  like_dislike_ratio_by_viewcounts_weighted  \
0                      0.969752                               69921.826086   
1                      0.969585                               70150.404005   
2                      0.972772                               64444.365869   
3                      0.971021                               59725.066775   
4                      0.972598                               70807.388299   
..                          ...                                        ...   
87                     0.956675                               12957.795705   
88                     0.960266                               25040.842574   
89                     0.954441                               15837.504011   
90                     0.958693                               18586.708998   
91                     0.958253                               40312.584142   

    percent_change action _merge  
0         0.044362    buy   both  
1         0.041791    buy   both  
2         0.022541   hold   both  
3         0.013192   hold   both  
4        -0.022469   hold   both  
..             ...    ...    ...  
87       -0.007472   hold   both  
88       -0.012718   hold   both  
89       -0.042660   sell   both  
90      